# Generated by Django 5.0.6 on 2025-12-17 19:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('social', '0003_profile_banner_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guild',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='🏰', max_length=10)),
                ('banner_url', models.URLField(blank=True)),
                ('guild_type', models.CharField(choices=[('interest', 'Common Interest'), ('organization', 'Organization'), ('project', 'Project/Goal'), ('custom', 'Custom')], default='custom', max_length=20)),
                ('layout', models.JSONField(blank=True, default=dict)),
                ('guild_settings', models.JSONField(blank=True, default=dict)),
                ('is_public', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('total_xp', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guilds_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guilds', to='social.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GuildChangeRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('change_type', models.CharField(choices=[('layout', 'Layout Change'), ('settings', 'Settings Change'), ('info', 'Info Change')], max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('proposed_changes', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='guilds.guild')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guild_change_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guild_changes_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GuildMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member')], default='member', max_length=20)),
                ('xp_contributed', models.PositiveIntegerField(default=0)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='guilds.guild')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guild_invites_sent', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guild_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['role', '-joined_at'],
            },
        ),
        migrations.CreateModel(
            name='GuildPoll',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('poll_type', models.CharField(choices=[('admin_vote', 'Admin Election'), ('task_approval', 'Task Approval'), ('habit_approval', 'Habit Approval'), ('change_approval', 'Change Approval'), ('points_update', 'Points Update'), ('custom', 'Custom Poll')], default='custom', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('options', models.JSONField(default=list)),
                ('change_preview', models.JSONField(blank=True, null=True)),
                ('related_id', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('passed', 'Passed'), ('failed', 'Failed')], default='active', max_length=20)),
                ('deadline', models.DateTimeField()),
                ('required_quorum', models.FloatField(default=0.5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guild_polls_created', to=settings.AUTH_USER_MODEL)),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polls', to='guilds.guild')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GuildPollVote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('option_index', models.PositiveSmallIntegerField()),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='guilds.guildpoll')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guild_poll_votes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='guild',
            index=models.Index(fields=['slug'], name='guilds_guil_slug_c695a6_idx'),
        ),
        migrations.AddIndex(
            model_name='guild',
            index=models.Index(fields=['guild_type'], name='guilds_guil_guild_t_8d375c_idx'),
        ),
        migrations.AddIndex(
            model_name='guild',
            index=models.Index(fields=['is_public'], name='guilds_guil_is_publ_d738bc_idx'),
        ),
        migrations.AddIndex(
            model_name='guildchangerequest',
            index=models.Index(fields=['guild', 'status'], name='guilds_guil_guild_i_ca715d_idx'),
        ),
        migrations.AddIndex(
            model_name='guildmembership',
            index=models.Index(fields=['guild', 'role'], name='guilds_guil_guild_i_f8efe6_idx'),
        ),
        migrations.AddIndex(
            model_name='guildmembership',
            index=models.Index(fields=['user'], name='guilds_guil_user_id_8f745f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='guildmembership',
            unique_together={('user', 'guild')},
        ),
        migrations.AddIndex(
            model_name='guildpoll',
            index=models.Index(fields=['guild', 'status'], name='guilds_guil_guild_i_4e9bd0_idx'),
        ),
        migrations.AddIndex(
            model_name='guildpoll',
            index=models.Index(fields=['deadline'], name='guilds_guil_deadlin_8651c8_idx'),
        ),
        migrations.AddIndex(
            model_name='guildpollvote',
            index=models.Index(fields=['poll', 'option_index'], name='guilds_guil_poll_id_afc2a2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='guildpollvote',
            unique_together={('poll', 'user')},
        ),
    ]
