# Generated by Django 5.0.6 on 2025-12-17 21:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuildHabit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='✅', max_length=10)),
                ('color', models.CharField(default='#10B981', max_length=20)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekdays', 'Weekdays'), ('weekly', 'Weekly')], default='daily', max_length=10)),
                ('point_value', models.PositiveIntegerField(default=5)),
                ('xp_reward', models.PositiveIntegerField(default=3)),
                ('participation_goal', models.PositiveIntegerField(default=80)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guild_habits_created', to=settings.AUTH_USER_MODEL)),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guild_habits', to='guilds.guild')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GuildHabitLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='guilds.guildhabit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guild_habit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='GuildTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('point_value', models.PositiveIntegerField(default=20)),
                ('xp_reward', models.PositiveIntegerField(default=15)),
                ('completion_type', models.CharField(choices=[('all', 'All Assignees'), ('majority', 'Majority Vote'), ('any', 'Any Assignee')], default='any', max_length=10)),
                ('is_completed', models.BooleanField(default=False)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ManyToManyField(blank=True, related_name='assigned_guild_tasks', to=settings.AUTH_USER_MODEL)),
                ('completed_by', models.ManyToManyField(blank=True, related_name='completed_guild_tasks', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guild_tasks_created', to=settings.AUTH_USER_MODEL)),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guild_tasks', to='guilds.guild')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GuildChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='🎯', max_length=10)),
                ('target_type', models.CharField(choices=[('tasks', 'Complete Tasks'), ('habits', 'Log Habits'), ('xp', 'Earn XP'), ('streak', 'Maintain Streak')], max_length=10)),
                ('target_value', models.PositiveIntegerField()),
                ('current_value', models.PositiveIntegerField(default=0)),
                ('xp_reward', models.PositiveIntegerField(default=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('failed', 'Failed')], default='active', max_length=10)),
                ('starts_at', models.DateTimeField()),
                ('deadline', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guild_challenges_created', to=settings.AUTH_USER_MODEL)),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='guilds.guild')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['guild', 'status'], name='guilds_guil_guild_i_3a38eb_idx'), models.Index(fields=['deadline'], name='guilds_guil_deadlin_513be6_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='guildhabit',
            index=models.Index(fields=['guild', 'is_active'], name='guilds_guil_guild_i_f28284_idx'),
        ),
        migrations.AddIndex(
            model_name='guildhabitlog',
            index=models.Index(fields=['habit', 'completed_at'], name='guilds_guil_habit_i_103844_idx'),
        ),
        migrations.AddIndex(
            model_name='guildhabitlog',
            index=models.Index(fields=['user', 'completed_at'], name='guilds_guil_user_id_2fc518_idx'),
        ),
        migrations.AddConstraint(
            model_name='guildhabitlog',
            constraint=models.UniqueConstraint(condition=models.Q(('completed_at__date', models.F('completed_at__date'))), fields=('habit', 'user'), name='unique_daily_guild_habit_log'),
        ),
        migrations.AddIndex(
            model_name='guildtask',
            index=models.Index(fields=['guild', 'is_completed'], name='guilds_guil_guild_i_a48c6b_idx'),
        ),
        migrations.AddIndex(
            model_name='guildtask',
            index=models.Index(fields=['due_date'], name='guilds_guil_due_dat_42d58d_idx'),
        ),
    ]
