# Generated by Django 5.0.6 on 2025-12-17 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0002_guildhabit_guildhabitlog_guildtask_guildchallenge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guild',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='guild_banners/'),
        ),
        migrations.AddField(
            model_name='guild',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='guild_logos/'),
        ),
    ]
