# Generated by Django 5.0.6 on 2026-05-11 11:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('niche_tag', models.CharField(blank=True, max_length=50)),
                ('is_public', models.BooleanField(default=True)),
                ('is_community', models.BooleanField(default=False)),
                ('save_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_lists', to=settings.AUTH_USER_MODEL)),
                ('forked_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forks', to='resources.resourcelist')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('description', models.TextField(blank=True, max_length=500)),
                ('resource_type', models.CharField(choices=[('tool', 'Tool'), ('reference', 'Reference'), ('community', 'Community'), ('tutorial', 'Tutorial'), ('other', 'Other')], default='tool', max_length=20)),
                ('is_free', models.BooleanField(default=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('upvote_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_resources', to=settings.AUTH_USER_MODEL)),
                ('resource_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='resources.resourcelist')),
            ],
            options={
                'ordering': ['position', '-upvote_count'],
            },
        ),
        migrations.CreateModel(
            name='ResourceUpvote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upvotes', to='resources.resource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_upvotes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSavedList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('resource_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='resources.resourcelist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-saved_at'],
            },
        ),
        migrations.AddIndex(
            model_name='resourcelist',
            index=models.Index(fields=['niche_tag', '-created_at'], name='resources_r_niche_t_8ed5a2_idx'),
        ),
        migrations.AddIndex(
            model_name='resourcelist',
            index=models.Index(fields=['creator', '-created_at'], name='resources_r_creator_f4e67d_idx'),
        ),
        migrations.AddIndex(
            model_name='resourcelist',
            index=models.Index(fields=['is_community', '-save_count'], name='resources_r_is_comm_c695e0_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['resource_list', 'position'], name='resources_r_resourc_b5ccf5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='resourceupvote',
            unique_together={('user', 'resource')},
        ),
        migrations.AlterUniqueTogether(
            name='usersavedlist',
            unique_together={('user', 'resource_list')},
        ),
    ]
