# Generated by Django 5.2.6 on 2025-12-13 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='banner_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
