# Generated by Django 5.0.6 on 2026-05-11 11:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('social', '0004_profile_display_name_profile_show_avatar_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('content', models.TextField()),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('draft', 'Draft')], default='public', max_length=10)),
                ('slug', models.CharField(blank=True, max_length=50)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='journal_entries', to='social.interest')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['author', 'visibility', '-created_at'], name='journal_jou_author__ee4a66_idx'), models.Index(fields=['-created_at'], name='journal_jou_created_b6c001_idx')],
                'unique_together': {('author', 'slug')},
            },
        ),
    ]
