# Generated by Django 5.0.6 on 2025-12-15 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='focus_session_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_active',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('online', 'Online'), ('idle', 'Idle'), ('focus', 'Focus'), ('dnd', 'Do Not Disturb'), ('offline', 'Offline')], default='offline', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='status_message',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
