# Generated by Django 5.2.6 on 2025-12-12 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='habitlog',
            index=models.Index(fields=['habit', '-date'], name='users_habit_habit_i_3f6906_idx'),
        ),
        migrations.AddIndex(
            model_name='habitlog',
            index=models.Index(fields=['date', 'completed'], name='users_habit_date_440754_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['user', 'status'], name='users_task_user_id_7b9210_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['user', '-created_at'], name='users_task_user_id_58cf90_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['due_date'], name='users_task_due_dat_56ac82_idx'),
        ),
        migrations.AddIndex(
            model_name='userinterest',
            index=models.Index(fields=['user', '-added_at'], name='users_useri_user_id_66c5c6_idx'),
        ),
    ]
