# Generated by Django 5.2.6 on 2025-12-13 00:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_dashboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='friend_upgrade_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='connection',
            name='friend_upgrade_requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='friend_upgrade_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
