# Generated by Django 5.2.6 on 2025-12-13 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitstreak',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
