# Generated by Django 5.0.6 on 2025-12-15 00:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0003_habitstreak_image_url_task_image_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('target_value', models.FloatField(default=100)),
                ('current_value', models.FloatField(default=0)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('category', models.CharField(choices=[('health', 'Health'), ('career', 'Career'), ('learning', 'Learning'), ('finance', 'Finance'), ('personal', 'Personal'), ('other', 'Other')], default='personal', max_length=20)),
                ('color', models.CharField(choices=[('pink', 'Pink'), ('green', 'Green'), ('yellow', 'Yellow'), ('blue', 'Blue'), ('purple', 'Purple'), ('cyan', 'Cyan')], default='cyan', max_length=20)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_completed'], name='productivit_user_id_ee1db0_idx'), models.Index(fields=['user', 'category'], name='productivit_user_id_ccf475_idx')],
            },
        ),
    ]
