# Generated by Django 5.0.6 on 2025-12-15 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0004_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitstreak',
            name='color',
            field=models.CharField(choices=[('blue', 'Blue'), ('purple', 'Purple'), ('pink', 'Pink'), ('red', 'Red'), ('orange', 'Orange'), ('yellow', 'Yellow'), ('green', 'Green'), ('cyan', 'Cyan'), ('indigo', 'Indigo')], default='blue', max_length=20),
        ),
        migrations.AddField(
            model_name='habitstreak',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', max_length=20),
        ),
    ]
