# Generated by Django 5.0.6 on 2025-12-15 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0005_habitstreak_color_habitstreak_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitstreak',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], db_column='target_frequency', default='daily', max_length=20),
        ),
    ]
