# Generated by Django 5.0.6 on 2025-12-15 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0006_fix_frequency_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('health', 'Health'), ('career', 'Career'), ('learning', 'Learning'), ('finance', 'Finance'), ('personal', 'Personal'), ('other', 'Other')], default='general', max_length=20),
        ),
    ]
