# Generated by Django 5.0.6 on 2025-12-17 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0007_alter_goal_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitstreak',
            name='point_value_per_completion',
            field=models.PositiveIntegerField(default=0, help_text='Points earned each time this habit is completed'),
        ),
        migrations.AddField(
            model_name='task',
            name='point_value',
            field=models.PositiveIntegerField(default=0, help_text='Points earned when task is completed'),
        ),
    ]
